#!/usr/bin/env python3
"""Check that the selected sextic geometry sector is generated by mu1 on H2O."""

from __future__ import annotations

import numpy as np

from compare_gaussian_sextic import (
    _aligned_model_from_gaussian,
    _c1_matrix,
    _c2_tensor,
    _didq_from_model,
    _modewise_proportionality_scalars,
    _mu1_mode_matrices,
    _quartic_tau_from_c1,
    _representation_axis_values,
    _zeta_xyz,
    sextic_breakdown_from_c1_hz,
    sextic_structural_breakdown_hz,
)
from gaussian_vpt_parser import align_gaussian_cubic_force_constants, parse_gaussian_anharmonic_force_data, parse_gaussian_quartic_benchmark


def main() -> None:
    model, _rep, _order, _signs, _didq_err = _aligned_model_from_gaussian("h2o.fchk", "h2o.log")
    anh = parse_gaussian_anharmonic_force_data("h2o.log")
    quart = parse_gaussian_quartic_benchmark("h2o.log")
    _, phi3_reduced_cm, _ = align_gaussian_cubic_force_constants(anh, np.abs(model.vib_freq_cm))

    freq_cm = np.abs(model.vib_freq_cm)
    pmom, rot_cm = _representation_axis_values(model)
    didq = _didq_from_model(model)
    c1 = _c1_matrix(didq, freq_cm, pmom)
    mu1 = _mu1_mode_matrices(model)
    scales = _modewise_proportionality_scalars(c1, mu1)
    c1_mu1 = scales[:, None, None] * mu1
    tau_mu1, _ = _quartic_tau_from_c1(c1_mu1, freq_cm)
    c2_mu1 = _c2_tensor(c1_mu1, _zeta_xyz(model), freq_cm, rot_cm)

    raw_mu1 = sextic_breakdown_from_c1_hz(c1_mu1, c2_mu1, tau_mu1, phi3_reduced_cm, freq_cm, rot_cm, quart.spectroscopic_axes)
    struct = sextic_structural_breakdown_hz(model, phi3_reduced_cm, quart.spectroscopic_axes)

    max_geom_err = 0.0
    for key, vals in raw_mu1.items():
        if "X1" in vals:
            geom = vals["X1"] - vals["X2"] + vals["X4"]
        elif "Y5" in vals:
            geom = vals["Y1"] - vals["Y2"] + vals["Y4"] + vals["Y5"] + vals["Y6"]
        else:
            geom = vals["Y1"] - vals["Y2"] + vals["Y4"]
        max_geom_err = max(max_geom_err, abs(geom - struct[key]["geometry_hz"]))

    print(f"max |geometry(mu1-generated) - geometry(model)| = {max_geom_err:.3e}")
    if max_geom_err > 1.0e-8:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
