#!/usr/bin/env python3
"""Check that the quartic tensor in the sextic geometry sector is generated by mu1."""

from __future__ import annotations

import numpy as np

from compare_gaussian_sextic import (
    _c1_matrix,
    _didq_from_model,
    _modewise_proportionality_scalars,
    _mu1_mode_matrices,
    _quartic_tau_from_c1,
    _quartic_tau_from_model,
    _representation_axis_values,
)
from gaussian_vpt_parser import parse_gaussian_fchk_harmonic_data
from rovib_distortion import harmonic_inertia_model_from_geometry_hessian


def main() -> None:
    fchk = parse_gaussian_fchk_harmonic_data("h2o.fchk")
    model = harmonic_inertia_model_from_geometry_hessian(
        fchk.masses_amu,
        fchk.coords_bohr * 0.529177210903,
        fchk.cartesian_force_constants,
        representation="I",
    )

    didq = _didq_from_model(model)
    freq_cm = np.abs(model.vib_freq_cm)
    pmom, _rot_cm = _representation_axis_values(model)
    c1 = _c1_matrix(didq, freq_cm, pmom)
    tau_model, taup_model = _quartic_tau_from_model(model)
    tau_c1, taup_c1 = _quartic_tau_from_c1(c1, freq_cm)

    mu1 = _mu1_mode_matrices(model)
    scales = _modewise_proportionality_scalars(c1, mu1)
    c1_from_mu1 = scales[:, None, None] * mu1
    tau_mu1, taup_mu1 = _quartic_tau_from_c1(c1_from_mu1, freq_cm)

    tau_c1_err = float(np.max(np.abs(tau_model - tau_c1)))
    taup_c1_err = float(np.max(np.abs(taup_model - taup_c1)))
    tau_mu1_err = float(np.max(np.abs(tau_model - tau_mu1)))
    taup_mu1_err = float(np.max(np.abs(taup_model - taup_mu1)))

    print(f"max |tau(model) - tau(c1)| on h2o = {tau_c1_err:.3e}")
    print(f"max |tau'(model) - tau'(c1)| on h2o = {taup_c1_err:.3e}")
    print(f"max |tau(model) - tau(mu1-scaled)| on h2o = {tau_mu1_err:.3e}")
    print(f"max |tau'(model) - tau'(mu1-scaled)| on h2o = {taup_mu1_err:.3e}")
    if max(tau_c1_err, taup_c1_err, tau_mu1_err, taup_mu1_err) > 1.0e-10:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
