#!/usr/bin/env python3
"""Exact linear quartic scalar basis in the CeDiTT4 spirit."""

from __future__ import annotations

import sympy as sp


def linear_quartic_scalar_basis() -> dict[str, object]:
    Jy, Jz = sp.symbols("Jy Jz")
    basis = sp.expand((Jy**2 + Jz**2) ** 2)
    coeffs = {
        "c_004": sp.expand(basis).coeff(Jz, 4).coeff(Jy, 0),
        "c_022": sp.expand(basis).coeff(Jz, 2).coeff(Jy, 2),
        "c_040": sp.expand(basis).coeff(Jz, 0).coeff(Jy, 4),
    }
    return {
        "basis_operator": basis,
        "plane_coefficients": coeffs,
        "statement": (
            "In the true linear limit the commuting quartic scalar space is "
            "one-dimensional and is generated by (J_perp^2)^2 = "
            "J_y^4 + 2 J_y^2 J_z^2 + J_z^4."
        ),
    }


if __name__ == "__main__":
    print(linear_quartic_scalar_basis())
