#!/usr/bin/env python3
"""Parity decomposition of homogeneous rotational monomials.

For invariance under the orthorhombic D2 subgroup generated by 180-degree
rotations about the x, y, z axes, a monomial Jx^a Jy^b Jz^c must satisfy

    a+b even, a+c even, b+c even,

equivalently: a, b, c have the same parity.

This gives:
- odd total degree: orthorhombic monomials have all exponents odd;
- even total degree: orthorhombic monomials have all exponents even.

The counts for degrees 3, 5, 6, 8 match the operator sectors used by
Watson--Aliev for S03, S05, H06, and H08.
"""

from __future__ import annotations

from math import comb


def homogeneous_degree_monomials(total_degree: int) -> list[tuple[int, int, int]]:
    out: list[tuple[int, int, int]] = []
    for a in range(total_degree + 1):
        for b in range(total_degree + 1 - a):
            c = total_degree - a - b
            out.append((a, b, c))
    return out


def is_orthorhombic_monomial(a: int, b: int, c: int) -> bool:
    return (a + b) % 2 == 0 and (a + c) % 2 == 0 and (b + c) % 2 == 0


def split_orthorhombic_monomials(total_degree: int) -> dict[str, object]:
    monoms = homogeneous_degree_monomials(total_degree)
    ortho = [m for m in monoms if is_orthorhombic_monomial(*m)]
    nonortho = [m for m in monoms if not is_orthorhombic_monomial(*m)]
    return {
        "degree": total_degree,
        "total_count": len(monoms),
        "orthorhombic_count": len(ortho),
        "nonorthorhombic_count": len(nonortho),
        "orthorhombic_monomials": tuple(ortho),
        "nonorthorhombic_monomials": tuple(nonortho),
    }


def closed_form_orthorhombic_count(total_degree: int) -> int:
    if total_degree % 2 == 0:
        n = total_degree // 2
        return comb(n + 2, 2)
    n = (total_degree - 3) // 2
    return comb(n + 2, 2)


def paper1_sector_count_summary() -> dict[str, dict[str, object]]:
    return {
        "S03": split_orthorhombic_monomials(3),
        "S05": split_orthorhombic_monomials(5),
        "S07": split_orthorhombic_monomials(7),
        "H06": split_orthorhombic_monomials(6),
        "H08": split_orthorhombic_monomials(8),
    }


def main() -> None:
    print(paper1_sector_count_summary())


if __name__ == "__main__":
    main()
