#!/usr/bin/env python3
"""Exact dependency audit for the fully defined printed H08 source blocks.

Scope:
    isolate the part of the Paper1 octic source hierarchy that is already fixed
    by explicit printed definitions, without guessing the unresolved one-index
    prime notation appearing in the visible bare H08 line.

Result:
    every fully defined printed source block used by H08 is mu2-free and lives
    in the algebra generated by mu1, phi4, zeta, omega, and B, while phi3
    enters only through the pure-vibrational generators S03/S05/S07 and H06.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Support:
    rot: frozenset[str]
    pot: frozenset[str]
    harm: frozenset[str]

    def union(self, *others: "Support") -> "Support":
        rot = set(self.rot)
        pot = set(self.pot)
        harm = set(self.harm)
        for other in others:
            rot |= set(other.rot)
            pot |= set(other.pot)
            harm |= set(other.harm)
        return Support(frozenset(rot), frozenset(pot), frozenset(harm))


ZERO = Support(frozenset(), frozenset(), frozenset())


def paper1_octic_defined_support_map() -> dict[str, Support]:
    out: dict[str, Support] = {}

    out["mu1"] = Support(frozenset({"mu1"}), frozenset(), frozenset())
    out["mu2"] = Support(frozenset({"mu2"}), frozenset(), frozenset())
    out["phi3"] = Support(frozenset(), frozenset({"phi3"}), frozenset())
    out["phi4"] = Support(frozenset(), frozenset({"phi4"}), frozenset())
    out["zeta"] = Support(frozenset(), frozenset(), frozenset({"zeta"}))
    out["omega"] = Support(frozenset(), frozenset(), frozenset({"omega"}))
    out["B"] = Support(frozenset(), frozenset(), frozenset({"B"}))

    # Printed Table-I / Eq.(101) content already fixed in the linear audit.
    out["C"] = out["mu1"]
    out["R_k"] = out["C"]
    out["R_tilde_k"] = out["R_k"]
    out["R_kl"] = ZERO.union(out["mu1"], out["phi4"], out["zeta"], out["omega"], out["B"])
    out["R'_kl"] = ZERO.union(out["R_kl"], out["R_k"], out["phi4"], out["omega"])

    # Notation block below Table V.
    out["H02"] = out["B"]
    out["X"] = ZERO.union(out["R_kl"], out["R'_kl"], out["R_tilde_k"], out["H02"], out["omega"])
    out["X_u"] = out["X"]
    out["E"] = ZERO.union(out["R'_kl"], out["R_tilde_k"], out["X"], out["H02"])
    out["E_u"] = ZERO.union(out["R'_kl"], out["R_tilde_k"], out["X_u"], out["H02"])
    out["F"] = ZERO.union(out["R'_kl"], out["R_tilde_k"], out["X"], out["H02"])
    out["F_u"] = ZERO.union(out["R'_kl"], out["R_tilde_k"], out["X_u"], out["H02"])
    out["U"] = ZERO.union(out["R_kl"], out["R'_kl"], out["R_tilde_k"], out["X"], out["omega"])
    out["V"] = ZERO.union(out["R_kl"], out["R'_kl"], out["R_tilde_k"], out["X"], out["omega"])

    # Pure-vibrational odd generators and sextic theorem input.
    out["H04"] = ZERO.union(out["mu1"], out["omega"])
    out["H06"] = ZERO.union(out["mu1"], out["phi3"], out["omega"], out["B"])
    out["S03"] = ZERO.union(out["phi3"], out["omega"])
    out["S05"] = ZERO.union(out["phi3"], out["phi4"], out["omega"])
    out["S07"] = ZERO.union(out["phi3"], out["phi4"], out["omega"])

    # The fully defined piece of H08 visible in the notation hierarchy.
    out["defined_H08_blocks"] = ZERO.union(
        out["R_k"],
        out["R_tilde_k"],
        out["R_kl"],
        out["R'_kl"],
        out["X"],
        out["X_u"],
        out["E"],
        out["E_u"],
        out["F"],
        out["F_u"],
        out["U"],
        out["V"],
        out["H02"],
        out["H04"],
        out["H06"],
        out["S03"],
        out["S05"],
        out["S07"],
    )
    return out


def paper1_octic_defined_block_verdict() -> dict[str, object]:
    dep = paper1_octic_defined_support_map()
    keys = (
        "R_k",
        "R_tilde_k",
        "R_kl",
        "R'_kl",
        "X",
        "X_u",
        "E",
        "E_u",
        "F",
        "F_u",
        "U",
        "V",
        "H02",
        "H04",
        "H06",
        "S03",
        "S05",
        "S07",
    )
    return {
        "audited_blocks": keys,
        "mu2_in_each_block": {key: ("mu2" in dep[key].rot) for key in keys},
        "mu2_in_defined_H08_blocks": ("mu2" in dep["defined_H08_blocks"].rot),
        "rotational_support_defined_H08": tuple(sorted(dep["defined_H08_blocks"].rot)),
        "potential_support_defined_H08": tuple(sorted(dep["defined_H08_blocks"].pot)),
        "harmonic_support_defined_H08": tuple(sorted(dep["defined_H08_blocks"].harm)),
        "unresolved_notation_left_out": ("R_klm", "bare H08 tail"),
    }


def main() -> None:
    print(paper1_octic_defined_block_verdict())


if __name__ == "__main__":
    main()
